[build]
  command = "npm run build"
  publish = ".next"

[context.deploy-preview.environment]
  NETLIFY_DRAWER = "false"
  NETLIFY_DEPLOY_PREVIEWS = "false"

[context.branch-deploy.environment]
  NETLIFY_DRAWER = "false"

[context.production.environment]
  NETLIFY_DRAWER = "false"
